import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import scss from 'rollup-plugin-scss';
import replace from '@rollup/plugin-replace';

const isProd = (process.env.BUILD === 'production');

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: './src/main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian', 'obsidian-dataview'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
    json(),
    scss({
      output: 'styles.css', 
      sass: require('sass'), 
      watch: ['./src/style/main.scss', 
      './src/style/regent.scss', 
      './src/style/modal.scss',
      './src/style/modal-presets.scss',
      './src/style/modal-table.scss',
      './src/style/sk.scss'] // idk why * no work
    }),
    replace({
      values: {
        '_isProd': isProd.toString()
      },
      'preventAssignment': true
    })
  ]
};
