site_name: Skribi
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: dusk
      toggle: 
        icon: material/toggle-switch-off-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
  icon: 
    repo: fontawesome/brands/github
    logo: az/feather
  features:
    - header.autohide
    - navigation.instant
  favicon: images/feather.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
repo_url: https://github.com/azulaloi/obsidian-skribi
repo_name: azulaloi/obsidian-skribi
