site_name: Skribi
site_url: https://azulaloi.github.io/obsidian-skribi/
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: dusk
      toggle: 
        icon: material/toggle-switch-off-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
  icon: 
    repo: fontawesome/brands/github
    logo: az/feather
  features:
    - header.autohide
    - navigation.instant
  favicon: images/feather.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
repo_url: https://github.com/azulaloi/obsidian-skribi
repo_name: azulaloi/obsidian-skribi
nav:
  - 'Outline': index.md
  - General Use:
    - 'Eta Syntax': syntax/eta.md
    - 'Skribi Syntax': syntax/skribi.md
    - 'Templates': syntax/templates.md
    - 'Template Metadata': syntax/template_metadata.md
    - 'Styling': syntax/style.md
  - Scripting:
    - 'Context': scripting/context.md
    - Modules: 
      - 'Skribi': scripting/modules/skribi.md
      - 'Scriptloader': scripting/modules/scriptloader.md
      - 'Integrations': scripting/modules/integrations.md
    - 'Examples': scripting/examples.md
    - 'Misc': scripting/errors.md
  - Miscellaneous:
    - 'Settings': settings.md
    - 'Commands': commands.md
    - 'Render Modal': misc/render_modal.md
    - 'Indicators': states.md
    - 'Localization': misc/localization.md